  name: CI-Coverity-Basic-demo
  on:
    push:
      branches: [ main, master, develop, stage, release ]
    pull_request:
      branches: [ main, master, develop, stage, release ]
    workflow_dispatch:

  jobs:
    build:
      runs-on: [ mac_khp_sh ]
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
        - name: Coverity Scan
          uses: blackduck-inc/black-duck-security-scan@v2
          with:
            ### SCANNING: Required fields
            # coverity_url: ${{ vars.COVERITY_URL }}
            # coverity_user: ${{ secrets.COVERITY_USER }}
            # coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
            # coverity_project_name: "Coverity_Demo"
            # coverity_stream_name: "Coverity_Demo"

            ###coverity connect userss -uncomment below
            coverity_url: ${{ secrets.COVERITY_CLASSIC_URL }}
            coverity_user: ${{ secrets.COVERITY_USER }}
            coverity_passphrase: ${{ secrets.COVERITY_CLASSIC_PWD }}
            coverity_project_name: "Coverity_Connect_Project_1"
            coverity_stream_name: "Coverity_Connect_Stream_1"
            coverity_local: true

            ### POLICY ENFORCEMENT: Uncomment to break build on policy
            #coverity_policy_view: 'Outstanding Issues'
            coverity_policy_view: '10006'

            ### PULL REQUEST COMMENTS:
            coverity_prComment_enabled: true
            ## Use the parameter below to add comments for issues filtered
            ## by impact. Default is High if unset
            ## NOTE: Issues matching coverity_policy_view are ignored if set
            # coverity_prComment_impacts: 'High,Medium,Low,Audit'
            github_token: ${{ secrets.GIT_PAT_TOKEN }} # Required when PR comments is enabled 

            # coverity_install_directory: "/Users/khp/Documents/install_Directory"

            # coverity_version: '2025.6.1'
            ### Mark build status if policy violating issues are found
            include_diagnostics: true
            mark_build_status: 'success'

        ### Uncomment below configuration to add custom logic based on return status
        # - name: cmdLine
        #   id: cmdLine
        #   run: |
        #     EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
        #     echo "Black Duck Security Scan exit status - $EXIT_CODE"

        - name: Save Logs
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: bridge-logs
            path: ${{ github.workspace }}/.bridge
            include-hidden-files: true

